### ISSUE TITLE
ACMEv2 Support

### ISSUE THREAD

**Issue by PedroTheIntern** [certbot/certbot-docker#17]
According to the email I received today from Let's Encrypt, it looks like ACMEv1 is being deprecated.

> Beginning June 1, 2020, we will stop allowing new domains to validate using
the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before
then, or certificate issuance will fail.
ACMEv1 API deprecation details can be found in our community forum:
https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1

**Comment by bmw** [comment]
Certbot has supported both ACMEv1 and ACMEv2 since March of 2018 and defaulted to ACMEv2 since July of 2018.

I suspect you have an explicit preference for ACMEv1 set somewhere such as `/etc/letsencrypt/cli.ini`. If you need help with configuring Certbot to use ACMEv2, I recommend making at post at https://community.letsencrypt.org where there is a large community of people familiar with the project who should be able to help you.
