### ISSUE TITLE
Update the core Dockerfile to use Python 3

### ISSUE THREAD

**Issue by creemama** [certbot/certbot-docker#4]
With the sunset of [Python 2 on January 1, 2020](https://pythonclock.org/), are there plans to update the [core Dockerfile](https://github.com/certbot-docker/certbot-docker/blob/master/core/Dockerfile) from using `python:2-alpine3.10` to `python:3-alpine3.10`?

Each of these [Certbot DNS plugins](https://hub.docker.com/r/certbot/certbot) supports Python >=3.4.
* [dns-dnsmadeeasy](https://pypi.org/project/certbot-dns-dnsmadeeasy)
* [dns-dnsimple](https://pypi.org/project/certbot-dns-dnsimple)
* [dns-ovh](https://pypi.org/project/certbot-dns-ovh)
* [dns-cloudflare](https://pypi.org/project/certbot-dns-cloudflare)
* [dns-cloudxns](https://pypi.org/project/certbot-dns-cloudxns)
* [dns-digitalocean](https://pypi.org/project/certbot-dns-digitalocean)
* [dns-google](https://pypi.org/project/certbot-dns-google)
* [dns-luadns](https://pypi.org/project/certbot-dns-luadns)
* [dns-nsone](https://pypi.org/project/certbot-dns-nsone)
* [dns-rfc2136](https://pypi.org/project/certbot-dns-rfc2136)
* [dns-route53](https://pypi.org/project/certbot-dns-route53)
* [dns-gehirn](https://pypi.org/project/certbot-dns-gehirn)
* [dns-linode](https://pypi.org/project/certbot-dns-linode)
* [dns-sakuracloud](https://pypi.org/project/certbot-dns-sakuracloud)

**Comment by bmw** [comment]
Yes. I was initially interested in trying to find a way to do this gradually so that it didn't suddenly break anyone's setup that was depending on the Python 2 installation in the Docker image, but I haven't heard any suggestions I liked there. In the absence of that, I think we can just make the change. There's more discussion about this at https://github.com/certbot/certbot/pull/6759.
